// src/themes/react/views/bare-ui/js/Pages/Hello.jsx
import { Link, Head } from '@inertiajs/react';

const Hello = ({ auth }) => {
    return (
        <>
            <Head title="Hello" />
            <div>
                <h1>Hello World from React</h1>
                <p>Current user: {auth?.user?.name ?? 'No auth is active'}</p>
                <Link href="/login">Go to Login</Link>
            </div>
        </>
    );
};

export default Hello;

// src/themes/svelte/views/js/Pages/Hello.svelte
<script>
    export let auth;

    let count = 0;

    const increment = () => {
        count++;
    };
</script>

<div>
    <h1>Hello World!</h1>
    <p>Current user: {auth?.user?.name ?? "No auth is active"}</p>
    <p>{count}</p>
    <button on:click={increment} class="bg-green-900">Increment</button>
</div>
